export const content = {
    en: {
        //? contenido de la ventana
        windowTitle: "My Portfolio",
        //? contenido de la ruta home
        homeTitle: "Hi!, I'm Franco",
        homeSpan11: "I'm a ",
        homeSpan12: `, with a strong will in programming and software that motivates me to continue every single day`,
        homeSpan21: `I’m motivated by finding all the potential and the benefits in practical solutions to complex problems, 
        always aiming to`,
        homeSpan31: `I am always eager to learn, adapt to different working methods, and follow various approaches, `,
        homeStrong11: "Computer Systems Engineering student",
        homeStrong21: "improve processes and deliver measurable results.",
        homeStrong31:
            "adjusting to the needs and the role assigned to me within the team.",
        homeCv: "Download My CV",
        homeContactme: "Contact me!",
        linkCV: "/assets/pdfs/CV - Franco André Calmette Miyazawa -en.pdf",
        //? contenido de la ruta projects
        projectsTitle: "Projects",
        //? contenido de la ruta contactme
        contactmeTitle: "Contact Me",
        contactmeSubTitle: "Find me here:",
        contactmeLabelName: "Name:",
        contactmeLabelEmail: "Email:",
        contacmeLabelMessage: "Message:",
        contactmeButtonSend: "Send",
        contactmeName: "Enter your name",
        contactmeEmail: "Enter yout email",
        contactmeMessage: "Enter your message (optional)",
        contactmeEmailError: "Invalid email address.",
        contactmeValidForm: "Form submitted successfully!",
        contactmeInvalidForm: "Incomplete or incorrect data.",
        contactmeUnexpectedError: "Unexpected error. Try to contact me by Gmail",
        contactmeEmailError: "Error while email was send. Try to contact me by Gmail",
        //? contenido de la ruta settings
        settingsTitle: "Settings",
        settingsLanguage: "Language:",
        settingsTheme: "Theme:",
        settingsSize: "Font size:",
        settingsFont: "Font type:",
        settingsLanguageOption1: "Spanish",
        settingsLanguageOption2: "English",
        settingsThemeOption1: "Light",
        settingsThemeOption2: "Dark",
        settingsSizeOption1: "Small",
        settingsSizeOption2: "Normal",
        settingsSizeOption3: "Large",
        settingsFontOption1: "Arial",
        settingsFontOption2: "Verdana",
        settingsFontOption3: "Tahoma"
    },
    es: {
        //? contenido de la ventana
        windowTitle: "Mi Portafolio",
        //? contenido de la ruta home
        homeTitle: "¡Hola!, Soy Franco",
        homeSpan11: "Soy un ",
        homeSpan12: `, con un gran interés por la programación y el software que me motiva a seguir cada día.`,
        homeSpan21: `Me motiva todo el potencial y los beneficios que se hayan mediante soluciones prácticas a problemas 
        complejos, siempre con la meta de`,
        homeSpan31: `Siempre estoy dispuesto a aprender, adaptarme a diferentes métodos de trabajo y seguir diversos 
        enfoques, `,
        homeStrong11: "Estudiante de Ingeniería de Sistemas Computacionales",
        homeStrong21: "mejorar procesos y generar resultados medibles.",
        homeStrong31:
            "ajustándome a las necesidades y al rol que se me asigne dentro del equipo.",
        homeCv: "Descargar Mi CV",
        homeContactme: "Contáctame",
        linkCV: "/assets/pdfs/CV - Franco André Calmette Miyazawa.pdf",
        //? contenido de la ruta projects
        projectsTitle: "Proyectos",
        //? contenido de la ruta contactme
        contactmeTitle: "Contáctame",
        contactmeSubTitle: "Encuéntrame aquí:",
        contactmeLabelName: "Nombre:",
        contactmeLabelEmail: "Email:",
        contacmeLabelMessage: "Mensaje:",
        contactmeButtonSend: "Enviar",
        contactmeName: "Ingrese su nombre",
        contactmeEmail: "Ingrese su correo",
        contactmeMessage: "Escriba un mensaje (opcional)",
        contactmeEmailError: "Correo inválido.",
        contactmeValidForm: "¡El formulario ha sido enviado correctamente!",
        contactmeInvalidForm: "El formulario esta incompleto o es incorrecto.",
        contactmeUnexpectedError: "Error inesperado, intenta contactarme por Gmail",
        contactmeEmailError: "Error al enviar correo, intenta contactarme por Gmail",
        //? contenido de la ruta settings
        settingsTitle: "Configuración",
        settingsLanguage: "Idioma:",
        settingsTheme: "Tema:",
        settingsSize: "Tamaño de fuente:",
        settingsFont: "Tipo de fuente:",
        settingsLanguageOption1: "Español",
        settingsLanguageOption2: "Inglés",
        settingsThemeOption1: "Claro",
        settingsThemeOption2: "Oscuro",
        settingsSizeOption1: "Pequeño",
        settingsSizeOption2: "Normal",
        settingsSizeOption3: "Grande",
        settingsFontOption1: "Arial",
        settingsFontOption2: "Verdana",
        settingsFontOption3: "Tahoma"
    },
};
